spring:
  datasource:
    url: jdbc:mysql://192.168.179.128:3308/spring_batch_demo?rewriteBatchedStatements=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30                  # 增加连接池大小（根据CPU核心数调整）
      minimum-idle: 10                        # 最小空闲连接数
      connection-timeout: 30000                # 连接超时时间（毫秒）
      max-lifetime: 1800000                   # 连接最大生命周期（30分钟）
      idle-timeout: 600000                    # 空闲连接超时（10分钟）
      connection-test-query: SELECT 1          # 用于验证连接的SQL
      leak-detection-threshold: 120000          # 检测连接泄漏的阈值（2分钟）
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

data:
  path: ${user.dir}/src/main/resources/data/


#logging:
#  level:
#    org:
#      springframework:
#        batch: DEBUG

