spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_demo?rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true